export BUCKFAST_PROJECT_ROOT=$PWD

export TONIC_HOME=$BUCKFAST_PROJECT_ROOT/send_pipe/tonic
export TONIC_TB_CFG_PATH=$TONIC_HOME/tb/config
export TONIC_TOOLS=$TONIC_HOME/tools

export PATH=$PATH:$TONIC_TOOLS
export PYTHONPATH=$PYTHONPATH:$TONIC_TOOLS/lib

export BASEJUMP_STL_ROOT=$BUCKFAST_PROJECT_ROOT/basejump_files
